[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200

lib_deps =
    bblanchon/ArduinoJson
    knolleary/PubSubClient
    br3ttb/PID
    adafruit/Adafruit MPU6050
    adafruit/Adafruit Unified Sensor
    adafruit/MAX6675 library
    waspinator/AccelStepper